export const tileValue = {
  blank: { size: "small", position: "-114px -57px" },
  one: { size: "small", position: "-2px -25px" },
  two: { size: "small", position: "-18px -25px" },
  three: { size: "small", position: "-34px -25px" },
  four: { size: "small", position: "-50px -25px" },
  five: { size: "small", position: "-66px -25px" },
  six: { size: "small", position: "-82px -25px" },
  seven: { size: "small", position: "-98px -25px" },
  eight: { size: "small", position: "-114px -25px" },
  flag: { size: "small", position: "-2px -41px" },
  falseFlag: { size: "small", position: "-18px -41px" },
  mine: { size: "small", position: "-34px -41px" },
  mystery: { size: "small", position: "-50px -41px" },
  happy: { size: "medium", position: "-2px -57px" },
  surprised: { size: "medium", position: "-28px -57px" },
  dead: { size: "medium", position: "-54px -57px" },
  victorious: { size: "medium", position: "-80px -57px" },
};
