export const tileValues = {
  blank: { size: "small", position: "-112px -55px" },
  one: { size: "small", position: "0 -23px" },
  two: { size: "small", position: "-16px -23px" },
  three: { size: "small", position: "-32px -23px" },
  four: { size: "small", position: "-48px -23px" },
  five: { size: "small", position: "-64px -23px" },
  six: { size: "small", position: "-80px -23px" },
  seven: { size: "small", position: "-96px -23px" },
  eight: { size: "small", position: "-112px -23px" },
  flag: { size: "small", position: "0 -39px" },
  falseFlag: { size: "small", position: "-16px -39px" },
  mine: { size: "small", position: "-32px -39px" },
  mystery: { size: "small", position: "-48px -39px" },
  happy: { size: "medium", position: "0 -55px" },
  surprised: { size: "medium", position: "-26px -55px" },
  dead: { size: "medium", position: "-52px -55px" },
  victorious: { size: "medium", position: "-78px -55px" },
};
